CREATE DATABASE CINEMA;
USE CINEMA;

CREATE TABLE CLIENTE(
ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
NOME_CLIENTE VARCHAR(100),
IDADE_CLIENTE TINYINT,
RG_CLIENTE INT
);

CREATE TABLE FILMES(
ID_FILME INT PRIMARY KEY AUTO_INCREMENT,
NOME_FILME VARCHAR(100),
CATEGORIA_FILME VARCHAR(100),
FAIXA_ETARIA CHAR,
DESCRICAO_FIME TEXT
);

CREATE TABLE SALAS(
ID_SALA INT PRIMARY KEY AUTO_INCREMENT,
NUMERO_SALA CHAR,
CATEGORIA_SALA ENUM('2D', '3D') DEFAULT '2D',
CAPACIDADE INT CHECK(CAPACIDADE > 0)
);

CREATE TABLE VENDA(
ID_VENDA INT PRIMARY KEY AUTO_INCREMENT,
VALOR_VENDA INT,
QNTD_INGRESSOS INT
);

CREATE TABLE INGRESSO(
ID_INGRESSO INT PRIMARY KEY AUTO_INCREMENT,
VALOR_INGRESSO INT,
QNTD_INGRESSOS INT,
ID_VENDA INT,
FOREIGN KEY (ID_VENDA) REFERENCES VENDA(ID_VENDA)
);
