CREATE DATABASE LOJA_ELETRONICOS;
USE LOJA_ELETRONICOS;

CREATE TABLE CLIENTES(
ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(100),
CPF CHAR,
TELEFONE INT
);

CREATE TABLE PRODUTOS(
ID_PRODUTO INT PRIMARY KEY auto_increment,
NOME_PRODUTO VARCHAR(100),
PRECO_PRODUTO INT,
CATEGORIA_PRODUTO VARCHAR(50),
MARCA_PRODUTO VARCHAR(50)
);

CREATE TABLE VENDAS(
ID_VENDA INT PRIMARY KEY AUTO_INCREMENT,
DATA_PRODUTO DATE,
VALOR_TOTAL INT
);

CREATE TABLE ESTOQUE(
ID_ESTOQUE INT PRIMARY KEY AUTO_INCREMENT,
QNTD_ESTOQUE INT,
ID_PRODUTO INT,
FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
);

CREATE TABLE PAGAMENTOS(
ID_PAGAMENTO INT PRIMARY KEY AUTO_INCREMENT,
QNTD_PAGAMENTOS INT,
TIPO_PAGAMENTO ENUM('PIX','CARTÃO','DINHEIRO')
);