CREATE DATABASE MANUTENCAO;
USE MANUTENCAO;

CREATE TABLE MAQUINAS(
ID_MAQUINA INT PRIMARY KEY AUTO_INCREMENT,
CODIGO_MAQUINA INT,
NOME_MAQUINA VARCHAR(100),
SETOR_MAQUINA VARCHAR(50),
DATA_AQUISICAO DATE
);

CREATE TABLE TECNICOS(
ID_TECNICO INT PRIMARY KEY AUTO_INCREMENT,
CPF_TECNICO CHAR,
ESPECIALIDADE_TECNICO TEXT
);

CREATE TABLE ORDENS(
ID_ORDEM INT PRIMARY KEY AUTO_INCREMENT,
DATA_ABERTURA DATE,
DATA_FECHAMENTO DATE,
SITUACAO ENUM('ABERTA', 'EM ANDAMENTO', 'CONCLUÍDA'),
ID_MAQUINA INT,
DESCRICAO TEXT,
TEMPO_GASTO TIME,
FOREIGN KEY(ID_MAQUINA) REFERENCES MAQUINAS(ID_MAQUINA)
);

CREATE TABLE PECAS(
ID_PECAS INT PRIMARY KEY AUTO_INCREMENT,
QUANTIDADE_UTILIZADA INT,
CUSTO_PECA INT
);

CREATE TABLE ESTOQUE(
ID_ESTOQUE INT PRIMARY KEY AUTO_INCREMENT,
ESTOQUE_DISPONIVEL INT,
ESTOQUE_MINIMO INT,
ID_PECAS INT,
FOREIGN KEY (ID_PECAS) REFERENCES PECAS(ID_PECAS)
);
